### ISSUE TITLE
libsidplayfp fails to build with VS 2022 17.8.3

### ISSUE THREAD

**Issue by stuerp** [libsidplayfp/libsidplayfp#109] opened 2024-01-01 12:15 UTC
* #include <memory> complains about "use of undefined type 'reSIDfp::Integrator6581': an include of "Integrator6581.h" in SID.h fixes this.
* Export "reSIDfp::Integrator6581::solve(int) const" is not found by the consumer of libsidplayfp.lib even though RESID_INLINING is specified during the build.

**Comment by drfiemost** [comment] 2024-01-01 19:35
Can you please post the compiler output? And did you define RESID_INLINE too?
Anyway I'm noticing now that filter->clock in SID.h is a virtual call so there's no much sense in marking the functions  inline.

**Comment by stuerp** [comment] 2024-01-01 20:49
This is the compiler output without modifying any of the library files:

21:46:15:040	1>(compiling source file 'residfp/SID.cpp')
21:46:15:040	1>C:\Users\Peter\Code\C++\Media\foobar2000\foo_sid\3rdParty\libsidplayfp\src\builders\residfp-builder\residfp\Filter6581.h(38,7):
21:46:15:040	1>see declaration of 'reSIDfp::Integrator6581'
21:46:15:040	1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3169,27):
21:46:15:040	1>the template instantiation context (the oldest one first) is
21:46:15:040	1>	C:\Users\Peter\Code\C++\Media\foobar2000\foo_sid\3rdParty\libsidplayfp\src\builders\residfp-builder\residfp\Filter6581.h(336,43):
21:46:15:040	1>	see reference to class template instantiation 'std::unique_ptr<reSIDfp::Integrator6581,std::default_delete<reSIDfp::Integrator6581>>' being compiled
21:46:15:040	1>	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3205,66):
21:46:15:040	1>	see reference to class template instantiation 'std::default_delete<reSIDfp::Integrator6581>' being compiled
21:46:15:040	1>	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3168,23):
21:46:15:040	1>	while compiling class template member function 'void std::default_delete<reSIDfp::Integrator6581>::operator ()(_Ty *) noexcept const'
21:46:15:040	1>        with
21:46:15:040	1>        [
21:46:15:040	1>            _Ty=reSIDfp::Integrator6581
21:46:15:040	1>        ]
21:46:15:040	1>		C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3280,33):
21:46:15:040	1>		see the first reference to 'std::default_delete<reSIDfp::Integrator6581>::operator ()' in 'std::unique_ptr<reSIDfp::Integrator6581,std::default_delete<reSIDfp::Integrator6581>>::~unique_ptr'
21:46:15:040	1>		C:\Users\Peter\Code\C++\Media\foobar2000\foo_sid\3rdParty\libsidplayfp\src\builders\residfp-builder\residfp\Filter6581.h(365,21):
21:46:15:040	1>		see the first reference to 'std::unique_ptr<reSIDfp::Integrator6581,std::default_delete<reSIDfp::Integrator6581>>::~unique_ptr' in 'reSIDfp::Filter6581::Filter6581'
21:46:15:040	1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3169,25): error C2338: static_assert failed: 'can't delete an incomplete type'
21:46:15:040	1>(compiling source file 'residfp/SID.cpp')
21:46:15:040	1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3170,9): warning C4150: deletion of pointer to incomplete type 'reSIDfp::Integrator6581'; no destructor called
21:46:15:040	1>(compiling source file 'residfp/SID.cpp')
21:46:15:040	1>C:\Users\Peter\Code\C++\Media\foobar2000\foo_sid\3rdParty\libsidplayfp\src\builders\residfp-builder\residfp\Filter6581.h(38,7):
21:46:15:040	1>see declaration of 'reSIDfp::Integrator6581'

**Comment by stuerp** [comment] 2024-01-01 20:54
Adding the Integrator6581.h header in SID.h fixes this:

#ifndef SIDFP_H
#define SIDFP_H

#include "Integrator6581.h"

#include <memory>

#include "siddefs-fp.h"

#include "sidcxx11.h"
...

**Comment by drfiemost** [comment] 2024-01-02 08:00
> 21:46:15:040 1> C:\Users\Peter\Code\C++\Media\foobar2000\foo_sid\3rdParty\libsidplayfp\src\builders\residfp-builder\residfp\Filter6581.h(365,21):
> 21:46:15:040 1> see the first reference to 'std::unique_ptr<reSIDfp::Integrator6581,std::default_deletereSIDfp::Integrator6581>::~unique_ptr' in 'reSIDfp::Filter6581::Filter6581'
> 21:46:15:040 1>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\memory(3169,25): error C2338: static_assert failed: 'can't delete an incomplete type' 

Ok, it seems the problem is in the Filter6581 constructor, so the include would go in Filter6581.h in place of the forward declaration or, alternatively, move the constructor implementation in the .cpp file.

But the best solution is to go back to raw pointers as smart pointer do more harm than good in this context.

**Comment by drfiemost** [comment] 2024-01-04 08:47
Should be fixed in master

**Closed** 2024-02-11 20:15 UTC
Labels: bug
